resp = {
    "status": {"error_code": "", "http_code": 200, "message": "Baked profile is ready"},
    "data": {
        "core": {
            "auto_update_core": True,
            "browser": {
                "browser_type": "mimic",
                "core_version": 132,
                "os_type": "windows",
            },
            "browser_version": "",
            "geolocation_fill_based_on_external_ip": True,
            "timezone_fill_based_on_external_ip": True,
        },
        "fingerprint": {
            "fonts": [
                "GenBkBasR",
                "DejaVu Math TeX Gyre",
                "Noto Serif Bold Italic",
                "Noto Naskh Arabic UI",
                "Amiri Quran",
                "Jet Brains Mono",
                "Noto Sans",
                "OpenSymbol",
                "Anton",
                "Noto Mono",
                "Arial",
                "Arial Italic",
                "Arial Bold",
                "Arial Bold Italic",
                "Arial Black",
                "Bahnschrift",
                "Calibri Light",
                "Calibri Light Italic",
                "Calibri",
                "Calibri Italic",
                "Calibri Bold",
                "Calibri Bold Italic",
                "Cambria",
                "Cambria Italic",
                "Cambria Bold",
                "Cambria Bold Italic",
                "Cambria Math",
                "Candara Light",
                "Candara Light Italic",
                "Candara",
                "Candara Italic",
                "Candara Bold",
                "Candara Bold Italic",
                "Comic Sans MS",
                "Comic Sans MS Italic",
                "Comic Sans MS Bold",
                "Comic Sans MS Bold Italic",
                "Consolas",
                "Consolas Italic",
                "Consolas Bold",
                "Consolas Bold Italic",
                "Constantia",
                "Constantia Italic",
                "Constantia Bold",
                "Constantia Bold Italic",
                "Corbel Light",
                "Corbel Light Italic",
                "Corbel",
                "Corbel Italic",
                "Corbel Bold",
                "Corbel Bold Italic",
                "Courier New",
                "Courier New Italic",
                "Courier New Bold",
                "Courier New Bold Italic",
                "Ebrima",
                "Ebrima Bold",
                "Franklin Gothic",
                "Franklin Gothic Medium",
                "Franklin Gothic Medium Italic",
                "Gabriola",
                "Gadugi",
                "Gadugi Bold",
                "Georgia",
                "Georgia Italic",
                "Georgia Bold",
                "Georgia Bold Italic",
                "HoloLens MDL2 Assets",
                "Impact",
                "Ink Free",
                "Javanese Text",
                "Leelawadee UI",
                "Leelawadee UI Semilight",
                "Leelawadee UI Bold",
                "Lucida Console",
                "Lucida Sans Unicode",
                "Malgun Gothic",
                "Malgun Gothic Bold",
                "Malgun Gothic Semilight",
                "Marlett",
                "Microsoft Himalaya",
                "Microsoft JhengHei Light",
                "Microsoft JhengHei",
                "Microsoft JhengHei Bold",
                "Microsoft JhengHei UI Light",
                "Microsoft JhengHei UI",
                "Microsoft JhengHei UI Bold",
                "Microsoft New Tai Lue",
                "Microsoft New Tai Lue Bold",
                "Microsoft PhagsPa",
                "Microsoft PhagsPa Bold",
                "Microsoft Sans Serif",
                "Microsoft Tai Le",
                "Microsoft Tai Le Bold",
                "Microsoft YaHei Light",
                "Microsoft YaHei",
                "Microsoft YaHei Bold",
                "Microsoft YaHei UI Light",
                "Microsoft YaHei UI",
                "Microsoft YaHei UI Bold",
                "Microsoft Yi Baiti",
                "MingLiU-ExtB",
                "PMingLiU-ExtB",
                "MingLiU_HKSCS-ExtB",
                "Mongolian Baiti",
                "MS Gothic",
                "MS PGothic",
                "MS UI Gothic",
                "MV Boli",
                "Myanmar Text",
                "Myanmar Text Bold",
                "Nirmala UI Semilight",
                "Nirmala UI",
                "Nirmala UI Bold",
                "Palatino Linotype",
                "Palatino Linotype Italic",
                "Palatino Linotype Bold",
                "Palatino Linotype Bold Italic",
                "Segoe MDL2 Assets",
                "Segoe Print",
                "Segoe Print Bold",
                "Segoe Script",
                "Segoe Script Bold",
                "Segoe UI Light",
                "Segoe UI Light Italic",
                "Segoe UI Semilight",
                "Segoe UI Semilight Italic",
                "Segoe UI",
                "Segoe UI Italic",
                "Segoe UI Semibold",
                "Segoe UI Semibold Italic",
                "Segoe UI Bold",
                "Segoe UI Bold Italic",
                "Segoe UI Black",
                "Segoe UI Black Italic",
                "Segoe UI Historic",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "SimSun",
                "NSimSun",
                "SimSun-ExtB",
                "Sitka Small",
                "Sitka Small Italic",
                "Sitka Small Bold",
                "Sitka Small Bold Italic",
                "Sitka Text",
                "Sitka Text Italic",
                "Sitka Text Bold",
                "Sitka Text Bold Italic",
                "Sitka Subheading",
                "Sitka Subheading Italic",
                "Sitka Subheading Bold",
                "Sitka Subheading Bold Italic",
                "Sitka Heading",
                "Sitka Heading Italic",
                "Sitka Heading Bold",
                "Sitka Heading Bold Italic",
                "Sitka Display",
                "Sitka Display Italic",
                "Sitka Display Bold",
                "Sitka Display Bold Italic",
                "Sitka Banner",
                "Sitka Banner Italic",
                "Sitka Banner Bold",
                "Sitka Banner Bold Italic",
                "Sylfaen",
                "Symbol",
                "Tahoma",
                "Tahoma Bold",
                "Times New Roman",
                "Times New Roman Italic",
                "Times New Roman Bold",
                "Times New Roman Bold Italic",
                "Trebuchet MS",
                "Trebuchet MS Italic",
                "Trebuchet MS Bold",
                "Trebuchet MS Bold Italic",
                "Verdana",
                "Verdana Italic",
                "Verdana Bold",
                "Verdana Bold Italic",
                "Webdings",
                "Wingdings",
                "Yu Gothic",
                "Yu Gothic Light",
                "Yu Gothic Regular",
                "Yu Gothic Medium",
                "Yu Gothic Bold",
                "Yu Gothic UI",
                "Yu Gothic UI Light",
                "Yu Gothic UI Semilight",
                "Yu Gothic UI Regular",
                "Yu Gothic UI Semibold",
                "Yu Gothic UI Bold",
            ],
            "geolocation": {
                "accuracy": 0,
                "altitude": 0,
                "latitude": 0,
                "longitude": 0,
            },
            "graphic": {
                "device_id": "9838",
                "renderer": "ANGLE (AMD, AMD Radeon(TM) R3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)",
                "vendor": "Google Inc. (AMD)",
                "vendor_id": "1002",
            },
            "localization": {
                "accept_languages": "en-US,en;q=0.9",
                "languages": "en-US,en",
                "locale": "en-US",
            },
            "media_devices": {"audio_inputs": 2, "audio_outputs": 1, "video_inputs": 1},
            "navigator": {
                "hardware_concurrency": 4,
                "max_touch_points": 0,
                "os_cpu": "",
                "platform": "Win32",
                "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.110 Safari/537.36",
            },
            "ports": [],
            "screen": {"height": 768, "pixel_ratio": 1, "width": 1366},
            "timezone": {"zone": ""},
        },
        "flags": {
            "audio_masking": "mask",
            "canvas_noise": "mask",
            "fonts_masking": "mask",
            "geolocation_masking": "mask",
            "geolocation_popup": "prompt",
            "graphics_masking": "mask",
            "graphics_noise": "mask",
            "localization_masking": "mask",
            "media_devices_masking": "mask",
            "navigator_masking": "mask",
            "ports_masking": "mask",
            "proxy_masking": "disabled",
            "quic_mode": "natural",
            "screen_masking": "mask",
            "startup_behavior": "recover",
            "timezone_masking": "mask",
            "webrtc_masking": "disabled",
        },
        "folder_id": "d5b59402-6368-46cb-be1e-2e56fd6f3d53",
        "is_local": False,
        "name": "Marisa Torres",
    },
}
data = {
    "data": {
        "core": {
            "auto_update_core": True,
            "browser": {
                "browser_type": "mimic",
                "core_version": 132,
                "os_type": "windows",
            },
            "browser_version": "",
            "geolocation_fill_based_on_external_ip": True,
            "timezone_fill_based_on_external_ip": True,
        },
        "fingerprint": {
            "fonts": [
                "GenBkBasR",
                "DejaVu Math TeX Gyre",
                "Noto Serif Bold Italic",
                "Noto Naskh Arabic UI",
                "Amiri Quran",
                "Jet Brains Mono",
                "Noto Sans",
                "OpenSymbol",
                "Anton",
                "Noto Mono",
                "Arial",
                "Arial Italic",
                "Arial Bold",
                "Arial Bold Italic",
                "Arial Black",
                "Bahnschrift",
                "Calibri Light",
                "Calibri Light Italic",
                "Calibri",
                "Calibri Italic",
                "Calibri Bold",
                "Calibri Bold Italic",
                "Cambria",
                "Cambria Italic",
                "Cambria Bold",
                "Cambria Bold Italic",
                "Cambria Math",
                "Candara Light",
                "Candara Light Italic",
                "Candara",
                "Candara Italic",
                "Candara Bold",
                "Candara Bold Italic",
                "Comic Sans MS",
                "Comic Sans MS Italic",
                "Comic Sans MS Bold",
                "Comic Sans MS Bold Italic",
                "Consolas",
                "Consolas Italic",
                "Consolas Bold",
                "Consolas Bold Italic",
                "Constantia",
                "Constantia Italic",
                "Constantia Bold",
                "Constantia Bold Italic",
                "Corbel Light",
                "Corbel Light Italic",
                "Corbel",
                "Corbel Italic",
                "Corbel Bold",
                "Corbel Bold Italic",
                "Courier New",
                "Courier New Italic",
                "Courier New Bold",
                "Courier New Bold Italic",
                "Ebrima",
                "Ebrima Bold",
                "Franklin Gothic",
                "Franklin Gothic Medium",
                "Franklin Gothic Medium Italic",
                "Gabriola",
                "Gadugi",
                "Gadugi Bold",
                "Georgia",
                "Georgia Italic",
                "Georgia Bold",
                "Georgia Bold Italic",
                "HoloLens MDL2 Assets",
                "Impact",
                "Ink Free",
                "Javanese Text",
                "Leelawadee UI",
                "Leelawadee UI Semilight",
                "Leelawadee UI Bold",
                "Lucida Console",
                "Lucida Sans Unicode",
                "Malgun Gothic",
                "Malgun Gothic Bold",
                "Malgun Gothic Semilight",
                "Marlett",
                "Microsoft Himalaya",
                "Microsoft JhengHei Light",
                "Microsoft JhengHei",
                "Microsoft JhengHei Bold",
                "Microsoft JhengHei UI Light",
                "Microsoft JhengHei UI",
                "Microsoft JhengHei UI Bold",
                "Microsoft New Tai Lue",
                "Microsoft New Tai Lue Bold",
                "Microsoft PhagsPa",
                "Microsoft PhagsPa Bold",
                "Microsoft Sans Serif",
                "Microsoft Tai Le",
                "Microsoft Tai Le Bold",
                "Microsoft YaHei Light",
                "Microsoft YaHei",
                "Microsoft YaHei Bold",
                "Microsoft YaHei UI Light",
                "Microsoft YaHei UI",
                "Microsoft YaHei UI Bold",
                "Microsoft Yi Baiti",
                "MingLiU-ExtB",
                "PMingLiU-ExtB",
                "MingLiU_HKSCS-ExtB",
                "Mongolian Baiti",
                "MS Gothic",
                "MS PGothic",
                "MS UI Gothic",
                "MV Boli",
                "Myanmar Text",
                "Myanmar Text Bold",
                "Nirmala UI Semilight",
                "Nirmala UI",
                "Nirmala UI Bold",
                "Palatino Linotype",
                "Palatino Linotype Italic",
                "Palatino Linotype Bold",
                "Palatino Linotype Bold Italic",
                "Segoe MDL2 Assets",
                "Segoe Print",
                "Segoe Print Bold",
                "Segoe Script",
                "Segoe Script Bold",
                "Segoe UI Light",
                "Segoe UI Light Italic",
                "Segoe UI Semilight",
                "Segoe UI Semilight Italic",
                "Segoe UI",
                "Segoe UI Italic",
                "Segoe UI Semibold",
                "Segoe UI Semibold Italic",
                "Segoe UI Bold",
                "Segoe UI Bold Italic",
                "Segoe UI Black",
                "Segoe UI Black Italic",
                "Segoe UI Historic",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "SimSun",
                "NSimSun",
                "SimSun-ExtB",
                "Sitka Small",
                "Sitka Small Italic",
                "Sitka Small Bold",
                "Sitka Small Bold Italic",
                "Sitka Text",
                "Sitka Text Italic",
                "Sitka Text Bold",
                "Sitka Text Bold Italic",
                "Sitka Subheading",
                "Sitka Subheading Italic",
                "Sitka Subheading Bold",
                "Sitka Subheading Bold Italic",
                "Sitka Heading",
                "Sitka Heading Italic",
                "Sitka Heading Bold",
                "Sitka Heading Bold Italic",
                "Sitka Display",
                "Sitka Display Italic",
                "Sitka Display Bold",
                "Sitka Display Bold Italic",
                "Sitka Banner",
                "Sitka Banner Italic",
                "Sitka Banner Bold",
                "Sitka Banner Bold Italic",
                "Sylfaen",
                "Symbol",
                "Tahoma",
                "Tahoma Bold",
                "Times New Roman",
                "Times New Roman Italic",
                "Times New Roman Bold",
                "Times New Roman Bold Italic",
                "Trebuchet MS",
                "Trebuchet MS Italic",
                "Trebuchet MS Bold",
                "Trebuchet MS Bold Italic",
                "Verdana",
                "Verdana Italic",
                "Verdana Bold",
                "Verdana Bold Italic",
                "Webdings",
                "Wingdings",
                "Yu Gothic",
                "Yu Gothic Light",
                "Yu Gothic Regular",
                "Yu Gothic Medium",
                "Yu Gothic Bold",
                "Yu Gothic UI",
                "Yu Gothic UI Light",
                "Yu Gothic UI Semilight",
                "Yu Gothic UI Regular",
                "Yu Gothic UI Semibold",
                "Yu Gothic UI Bold",
            ],
            "geolocation": {
                "accuracy": 0,
                "altitude": 0,
                "latitude": 0,
                "longitude": 0,
            },
            "graphic": {
                "device_id": "9838",
                "renderer": "ANGLE (AMD, AMD Radeon(TM) R3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)",
                "vendor": "Google Inc. (AMD)",
                "vendor_id": "1002",
            },
            "localization": {
                "accept_languages": "en-US,en;q=0.9",
                "languages": "en-US,en",
                "locale": "en-US",
            },
            "media_devices": {"audio_inputs": 2, "audio_outputs": 1, "video_inputs": 1},
            "navigator": {
                "hardware_concurrency": 4,
                "os_cpu": "",
                "platform": "Win32",
                "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.110 Safari/537.36",
            },
            "ports": [],
            "screen": {"height": 768, "pixel_ratio": 1, "width": 1366},
            "timezone": {"zone": ""},
        },
        "flags": {
            "audio_masking": "mask",
            "fonts_masking": "mask",
            "geolocation_masking": "mask",
            "geolocation_popup": "prompt",
            "graphics_masking": "mask",
            "graphics_noise": "mask",
            "localization_masking": "mask",
            "media_devices_masking": "mask",
            "navigator_masking": "mask",
            "ports_masking": "mask",
            "proxy_masking": "disabled",
            "quic_mode": "natural",
            "screen_masking": "mask",
            "timezone_masking": "mask",
            "webrtc_masking": "disabled",
        },
        "is_local": False,
        "name": "Marisa Torres",
    },
    "status": {"error_code": "", "http_code": 200, "message": "Baked profile is ready"},
}

print(data == resp)