name: Launcher Regression

on:
    workflow_dispatch:
        inputs:
            launcher_url_version:
                description: 'Specific launcher version to get the correct URL'
                required: true
                default: 'v1'
                type: choice
                options:
                  - v1
                  - v2
                  - v3
            backend_env:
                description: 'Backend environment to run tests against'
                required: true
                default: 'DEV'
                type: choice
                options:
                    - DEV
                    - QA
                    - STAGING-EU
                    - Multilogin EU
                    - INDIGO_PROD
                    - INDIGO_DEV
                    - MLX_LT
jobs:
    test:
        runs-on: ubuntu-latest
        environment: ${{ inputs.backend_env }}
        env:
            EMAIL: ${{ vars.EMAIL }}
            PASSWORD: ${{ vars.PASSWORD }}
            ENV: ${{ inputs.backend_env }}
            LAUNCHER_VER: ${{ inputs.launcher_version }}        
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
            cache: 'pip'
            cache-dependency-path: requirements.txt

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        - name: Set up Adapter
          run: |
                set -e
                ADAPTER_DIR=/home/runner/mlx/deps/adapter_tester
                mkdir -p $ADAPTER_DIR
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/adapter_tester/1.0.0/linux/adapter-amd64.bin -O $ADAPTER_DIR/adapter.bin
                chmod +x $ADAPTER_DIR/adapter.bin
                echo "1.0" > $ADAPTER_DIR/VERSION
        
        - name: Set up Launcher
          run: |
                set -e
                LAUNCHER_DIR=/home/runner/mlx/deps/launcher
                mkdir -p $LAUNCHER_DIR
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/CORE-1624/launcher-linux_amd64_CORE-1624.bin -O $LAUNCHER_DIR/launcher.bin
                chmod +x $LAUNCHER_DIR/launcher.bin
        
        - name: Start Launcher
          run: |
                set -e
                export ADAPTER_TESTER=1
                if [ $ENV == "DEV" ]; then
                /home/runner/mlx/deps/launcher/launcher.bin -gw-env=dev
                elif [ $ENV == "Multilogin EU" ]; then
                /home/runner/mlx/deps/launcher/launcher.bin &
                sleep 2 # Allow some time for the launcher to initialize
        
        - name: Start test
          run:  |
                set -e
                pytest tests/test_launcher_regression.py --html=report.html
        
        - name: Upload HTML Report as Artifact
          uses: actions/upload-artifact@v4
          with:
                name: pytest-report
                path: report.html